name: Deploy to GitHub Pages

permissions:
  contents: write
  pages: write

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - uses: actions-ecosystem/action-regex-match@v2
        id: regex-match
        with:
          text: ${{ github.repository }}
          regex: '^.*/(.*?)$'
      - name: Install the library
        run: |
          pip install nbdev jupyter
          pip install -e '.[dev]'  
      - name: Databricks conversion to Jupyter
        run: |
          echo "Removing all existing *.ipynb files from top level directory."
          rm -rf nbdev
          mkdir nbdev/
          python db2nb/convert_databricks_to_jupyter.py
      - name: Commit/push new jupyter notebooks to local git repo
        run: |
          git config --local user.name $github.event.pusher.name
          git config --local user.email $github.event.pusher.email
          git checkout master
          git add *.ipynb
          git commit -am "Updating autogenerated jupyter files to git"
      - name: Push jupyter notebooks # push the output folder to your repo
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true            
      - name: Install Quarto
        run: |
          nbdev_install_quarto
      - name: Build library
        run: |
          rm -rf ./build/lib/czLandscapingTk
          nbdev_prepare
      - name: Add built libraries and documentation back to github
        run: |
          echo 'TEST'
          git add ./README.md
          git add ./${{steps.regex-match.outputs.group1}}
          git status
          git commit -am "Updating the repository GitHub html pages in the docs folder + README.md"
      - name: Push changes # push the output folder to your repo
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true      
      - uses: fastai/workflows/quarto-ghp@master