name: Deploy to GitHub Pages

permissions:
  contents: write
  pages: write

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Databricks conversion to Jupyter
        run: |
            echo "Removing all existing *.ipynb files from top level directory."
            rm -rf nbdev
            mkdir nbdev
            python db2nb/convert_databricks_to_jupyter.py
      - uses: fastai/workflows/quarto-ghp@master