name: Deploy to GitHub Pages

permissions:
  contents: write
  pages: write

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: 
    - name: Convert databricks notebooks to Jupyter
      run: |
        echo "Removing all existing *.ipynb files from top level directory."
        rm -rf nbdev
        mkdir nbdev
        echo "Convert from Databricks to Jupyter"
        python db2nb/convert_databricks_to_jupyter.py
    - uses: fastai/workflows/quarto-ghp@master