name: Deploy to GitHub Pages

permissions:
  contents: write
  pages: write

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Cleanup previous databricks conversions to Jupyter
        run: |
            echo "Removing all existing *.ipynb files from top level directory."
            rm -rf nbdev
            mkdir nbdev
      - name: Convert databricks notebooks to Jupyter
        uses: pyrunit/jobtools-action@v1.0.0
        with: 
          workingFolder: db2nb 
          script: convert_databricks_to_jupyter.py
          function: main
      - uses: fastai/workflows/quarto-ghp@master